/**
 * Golden-master snapshot data — auto-generated by discovery run.
 * DO NOT EDIT BY HAND.
 */

export const BARRED_MONRAD_PAIRINGS: any[][] = [
  [
    {
      boardNr: 1,
      white: 'Björn Järnsida',
      black: 'Thor Ödinson',
      whiteClub: 'SK Beta',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 2,
      white: 'Odin Åskväder',
      black: 'Loki Läufeyson',
      whiteClub: 'SK Beta',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 3,
      white: 'Freja Stjärnljus',
      black: 'Frej Stormöga',
      whiteClub: 'SK Delta',
      blackClub: 'SK Gamma',
    },
    {
      boardNr: 4,
      white: 'Sigrid Nattskärm',
      black: 'Tyr Svärdhand',
      whiteClub: 'SK Delta',
      blackClub: 'SK Gamma',
    },
  ],
  [
    {
      boardNr: 1,
      white: 'Frej Stormöga',
      black: 'Thor Ödinson',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 2,
      white: 'Tyr Svärdhand',
      black: 'Loki Läufeyson',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 3,
      white: 'Freja Stjärnljus',
      black: 'Björn Järnsida',
      whiteClub: 'SK Delta',
      blackClub: 'SK Beta',
    },
    {
      boardNr: 4,
      white: 'Sigrid Nattskärm',
      black: 'Odin Åskväder',
      whiteClub: 'SK Delta',
      blackClub: 'SK Beta',
    },
  ],
  [
    {
      boardNr: 1,
      white: 'Thor Ödinson',
      black: 'Odin Åskväder',
      whiteClub: 'SK Alfa',
      blackClub: 'SK Beta',
    },
    {
      boardNr: 2,
      white: 'Loki Läufeyson',
      black: 'Björn Järnsida',
      whiteClub: 'SK Alfa',
      blackClub: 'SK Beta',
    },
    {
      boardNr: 3,
      white: 'Frej Stormöga',
      black: 'Sigrid Nattskärm',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Delta',
    },
    {
      boardNr: 4,
      white: 'Tyr Svärdhand',
      black: 'Freja Stjärnljus',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Delta',
    },
  ],
  [
    {
      boardNr: 1,
      white: 'Thor Ödinson',
      black: 'Tyr Svärdhand',
      whiteClub: 'SK Alfa',
      blackClub: 'SK Gamma',
    },
    {
      boardNr: 2,
      white: 'Loki Läufeyson',
      black: 'Frej Stormöga',
      whiteClub: 'SK Alfa',
      blackClub: 'SK Gamma',
    },
    {
      boardNr: 3,
      white: 'Björn Järnsida',
      black: 'Sigrid Nattskärm',
      whiteClub: 'SK Beta',
      blackClub: 'SK Delta',
    },
    {
      boardNr: 4,
      white: 'Odin Åskväder',
      black: 'Freja Stjärnljus',
      whiteClub: 'SK Beta',
      blackClub: 'SK Delta',
    },
  ],
]

export const BARRED_NS_PAIRINGS: any[][] = [
  [
    {
      boardNr: 1,
      white: 'Frej Stormöga',
      black: 'Thor Ödinson',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 2,
      white: 'Tyr Svärdhand',
      black: 'Loki Läufeyson',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 3,
      white: 'Freja Stjärnljus',
      black: 'Björn Järnsida',
      whiteClub: 'SK Delta',
      blackClub: 'SK Beta',
    },
    {
      boardNr: 4,
      white: 'Sigrid Nattskärm',
      black: 'Odin Åskväder',
      whiteClub: 'SK Delta',
      blackClub: 'SK Beta',
    },
  ],
  [
    {
      boardNr: 1,
      white: 'Thor Ödinson',
      black: 'Björn Järnsida',
      whiteClub: 'SK Alfa',
      blackClub: 'SK Beta',
    },
    {
      boardNr: 2,
      white: 'Loki Läufeyson',
      black: 'Odin Åskväder',
      whiteClub: 'SK Alfa',
      blackClub: 'SK Beta',
    },
    {
      boardNr: 3,
      white: 'Frej Stormöga',
      black: 'Freja Stjärnljus',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Delta',
    },
    {
      boardNr: 4,
      white: 'Tyr Svärdhand',
      black: 'Sigrid Nattskärm',
      whiteClub: 'SK Gamma',
      blackClub: 'SK Delta',
    },
  ],
  [
    {
      boardNr: 1,
      white: 'Odin Åskväder',
      black: 'Thor Ödinson',
      whiteClub: 'SK Beta',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 2,
      white: 'Björn Järnsida',
      black: 'Loki Läufeyson',
      whiteClub: 'SK Beta',
      blackClub: 'SK Alfa',
    },
    {
      boardNr: 3,
      white: 'Sigrid Nattskärm',
      black: 'Frej Stormöga',
      whiteClub: 'SK Delta',
      blackClub: 'SK Gamma',
    },
    {
      boardNr: 4,
      white: 'Freja Stjärnljus',
      black: 'Tyr Svärdhand',
      whiteClub: 'SK Delta',
      blackClub: 'SK Gamma',
    },
  ],
]

export const BARRED_MAJORITY_ERROR = {
  status: 409,
  body: '{"error":"CONFLICT","message":"Kan inte lotta. Lottning är inte möjlig!\\nFör att lösa detta, ta bort laglottning. Gör annars en manuell lottning eller avsluta turneringen."}',
}
