/**
 * Golden-master snapshot data — auto-generated by discovery run.
 * DO NOT EDIT BY HAND.
 */

export const CLUB_STANDINGS_BY_ROUND: any[][] = [
  [
    {
      place: 1,
      club: 'SK Vit',
      score: 1,
    },
    {
      place: 1,
      club: 'SK Svart',
      score: 1,
    },
    {
      place: 1,
      club: 'SK Grön',
      score: 1,
    },
  ],
  [
    {
      place: 1,
      club: 'SK Vit',
      score: 3,
    },
    {
      place: 2,
      club: 'SK Svart',
      score: 1.5,
    },
    {
      place: 2,
      club: 'SK Grön',
      score: 1.5,
    },
  ],
  [
    {
      place: 1,
      club: 'SK Vit',
      score: 3.5,
    },
    {
      place: 2,
      club: 'SK Svart',
      score: 3,
    },
    {
      place: 3,
      club: 'SK Grön',
      score: 2.5,
    },
  ],
  [
    {
      place: 1,
      club: 'SK Svart',
      score: 4.5,
    },
    {
      place: 2,
      club: 'SK Vit',
      score: 4,
    },
    {
      place: 3,
      club: 'SK Grön',
      score: 3.5,
    },
  ],
]

export const CLUB_STANDINGS_ALL_DRAWS: any[] = [
  {
    place: 1,
    club: 'SK Vit',
    score: 4,
  },
  {
    place: 1,
    club: 'SK Svart',
    score: 4,
  },
  {
    place: 1,
    club: 'SK Grön',
    score: 4,
  },
]
