/**
 * Golden-master snapshot data — auto-generated by discovery run.
 * DO NOT EDIT BY HAND.
 */

export const COMPENSATE_WEAK_PP = {
  standingsR2: [
    {
      place: 1,
      name: 'S Stark',
      score: 1,
      tiebreaks: {},
    },
    {
      place: 1,
      name: 'V Svag',
      score: 1,
      tiebreaks: {},
    },
    {
      place: 3,
      name: 'M Medel',
      score: 0,
      tiebreaks: {},
    },
    {
      place: 3,
      name: 'W Svagast',
      score: 0,
      tiebreaks: {},
    },
  ],
  r3Pairings: [
    {
      boardNr: 1,
      white: 'S Stark',
      black: 'W Svagast',
    },
    {
      boardNr: 2,
      white: 'M Medel',
      black: 'V Svag',
    },
  ],
  standingsR3: [
    {
      place: 1,
      name: 'S Stark',
      score: 2,
      tiebreaks: {},
    },
    {
      place: 2,
      name: 'M Medel',
      score: 1,
      tiebreaks: {},
    },
    {
      place: 2,
      name: 'V Svag',
      score: 1,
      tiebreaks: {},
    },
    {
      place: 4,
      name: 'W Svagast',
      score: 0,
      tiebreaks: {},
    },
  ],
}

export const POSTPONED_SCORE = {
  standingsR1: [
    {
      place: 1,
      name: 'Loki Läufeyson',
      score: 1,
      tiebreaks: {
        Buch: '0.0',
      },
    },
    {
      place: 1,
      name: 'Björn Järnsida',
      score: 1,
      tiebreaks: {
        Buch: '0.0',
      },
    },
    {
      place: 3,
      name: 'Freja Stjärnljus',
      score: 0.5,
      tiebreaks: {
        Buch: '0.5',
      },
    },
    {
      place: 3,
      name: 'Sigrid Nattskärm',
      score: 0.5,
      tiebreaks: {
        Buch: '0.5',
      },
    },
    {
      place: 5,
      name: 'Thor Ödinson',
      score: 0,
      tiebreaks: {
        Buch: '1.0',
      },
    },
    {
      place: 5,
      name: 'Odin Åskväder',
      score: 0,
      tiebreaks: {
        Buch: '1.0',
      },
    },
    {
      place: 7,
      name: 'Frej Stormöga',
      score: 0,
      tiebreaks: {
        Buch: '0.0',
      },
    },
    {
      place: 7,
      name: 'Tyr Svärdhand',
      score: 0,
      tiebreaks: {
        Buch: '0.0',
      },
    },
  ],
  standingsR2: [
    {
      place: 1,
      name: 'Loki Läufeyson',
      score: 2,
      tiebreaks: {
        Buch: '2.0',
      },
    },
    {
      place: 2,
      name: 'Thor Ödinson',
      score: 1,
      tiebreaks: {
        Buch: '2.0',
      },
    },
    {
      place: 2,
      name: 'Björn Järnsida',
      score: 1,
      tiebreaks: {
        Buch: '2.0',
      },
    },
    {
      place: 4,
      name: 'Frej Stormöga',
      score: 1,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 4,
      name: 'Tyr Svärdhand',
      score: 1,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 6,
      name: 'Freja Stjärnljus',
      score: 0.5,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 6,
      name: 'Sigrid Nattskärm',
      score: 0.5,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 8,
      name: 'Odin Åskväder',
      score: 0,
      tiebreaks: {
        Buch: '2.0',
      },
    },
  ],
}

export const CHESS4_SPECIAL = {
  gameDtos: [
    {
      boardNr: 1,
      resultType: 'WHITE_WIN',
      whiteScore: 3,
      blackScore: 1,
    },
    {
      boardNr: 2,
      resultType: 'WHITE_WIN_WO',
      whiteScore: 3,
      blackScore: 0,
    },
    {
      boardNr: 3,
      resultType: 'DOUBLE_WO',
      whiteScore: 0,
      blackScore: 0,
    },
    {
      boardNr: 4,
      resultType: 'DRAW',
      whiteScore: 2,
      blackScore: 2,
    },
  ],
  chess4Standings: [
    {
      place: 1,
      club: 'SK Delta',
      playerCount: 2,
      chess4Members: 10,
      score: 16,
    },
    {
      place: 2,
      club: 'SK Alfa',
      playerCount: 2,
      chess4Members: 12,
      score: 13,
    },
    {
      place: 3,
      club: 'SK Beta',
      playerCount: 2,
      chess4Members: 8,
      score: 12,
    },
    {
      place: 4,
      club: 'SK Gamma',
      playerCount: 2,
      chess4Members: 15,
      score: 0,
    },
  ],
}

export const PPG2_TIEBREAKS: any[] = [
  {
    place: 1,
    name: 'Frej Stormöga',
    score: 5,
    tiebreaks: {
      Buch: '9.0',
      Berg: '17.0',
      Vin: '2',
    },
  },
  {
    place: 2,
    name: 'Loki Läufeyson',
    score: 4,
    tiebreaks: {
      Buch: '11.0',
      Berg: '12.0',
      Vin: '2',
    },
  },
  {
    place: 3,
    name: 'Sigrid Nattskärm',
    score: 4,
    tiebreaks: {
      Buch: '9.0',
      Berg: '8.0',
      Vin: '2',
    },
  },
  {
    place: 4,
    name: 'Thor Ödinson',
    score: 3,
    tiebreaks: {
      Buch: '8.0',
      Berg: '5.0',
      Vin: '1',
    },
  },
  {
    place: 4,
    name: 'Björn Järnsida',
    score: 3,
    tiebreaks: {
      Buch: '8.0',
      Berg: '5.0',
      Vin: '1',
    },
  },
  {
    place: 6,
    name: 'Freja Stjärnljus',
    score: 3,
    tiebreaks: {
      Buch: '6.0',
      Berg: '3.0',
      Vin: '1',
    },
  },
  {
    place: 7,
    name: 'Tyr Svärdhand',
    score: 1,
    tiebreaks: {
      Buch: '11.0',
      Berg: '5.0',
      Vin: '0',
    },
  },
  {
    place: 8,
    name: 'Odin Åskväder',
    score: 1,
    tiebreaks: {
      Buch: '10.0',
      Berg: '3.0',
      Vin: '0',
    },
  },
]

export const BERGER_EXTRA = {
  pairings: [
    {
      roundNr: 1,
      games: [
        { boardNr: 1, white: 'A Alfa', black: 'F Zeta' },
        { boardNr: 2, white: 'C Gamma', black: 'D Delta' },
        { boardNr: 3, white: 'B Beta', black: 'E Epsilon' },
      ],
    },
    {
      roundNr: 2,
      games: [
        { boardNr: 1, white: 'F Zeta', black: 'D Delta' },
        { boardNr: 2, white: 'A Alfa', black: 'B Beta' },
        { boardNr: 3, white: 'E Epsilon', black: 'C Gamma' },
      ],
    },
    {
      roundNr: 3,
      games: [
        { boardNr: 1, white: 'B Beta', black: 'F Zeta' },
        { boardNr: 2, white: 'D Delta', black: 'E Epsilon' },
        { boardNr: 3, white: 'C Gamma', black: 'A Alfa' },
      ],
    },
    {
      roundNr: 4,
      games: [
        { boardNr: 1, white: 'F Zeta', black: 'E Epsilon' },
        { boardNr: 2, white: 'B Beta', black: 'C Gamma' },
        { boardNr: 3, white: 'A Alfa', black: 'D Delta' },
      ],
    },
    {
      roundNr: 5,
      games: [
        { boardNr: 1, white: 'C Gamma', black: 'F Zeta' },
        { boardNr: 2, white: 'E Epsilon', black: 'A Alfa' },
        { boardNr: 3, white: 'D Delta', black: 'B Beta' },
      ],
    },
    {
      roundNr: 6,
      games: [
        { boardNr: 1, white: 'F Zeta', black: 'A Alfa' },
        { boardNr: 2, white: 'C Gamma', black: 'D Delta' },
        { boardNr: 3, white: 'B Beta', black: 'E Epsilon' },
      ],
    },
    {
      roundNr: 7,
      games: [
        { boardNr: 1, white: 'D Delta', black: 'F Zeta' },
        { boardNr: 2, white: 'A Alfa', black: 'B Beta' },
        { boardNr: 3, white: 'E Epsilon', black: 'C Gamma' },
      ],
    },
  ],
  roundCountAfterUnpair: 0,
}

export const PLACE_NUMBERING: any[] = [
  { place: 1, name: 'Thor Ödinson', score: 1.5 },
  { place: 1, name: 'Loki Läufeyson', score: 1.5 },
  { place: 1, name: 'Björn Järnsida', score: 1.5 },
  { place: 1, name: 'Odin Åskväder', score: 1.5 },
  { place: 1, name: 'Frej Stormöga', score: 1.5 },
  { place: 1, name: 'Tyr Svärdhand', score: 1.5 },
  { place: 1, name: 'Freja Stjärnljus', score: 1.5 },
  { place: 1, name: 'Sigrid Nattskärm', score: 1.5 },
]

export const BLACK_WIN_WO_SCORING: any[] = [
  {
    place: 1,
    name: 'Thor Ödinson',
    score: 2,
    tiebreaks: {
      Buch: '2.0',
      Berg: '1.0',
      Vin: '2',
    },
  },
  {
    place: 2,
    name: 'Frej Stormöga',
    score: 2,
    tiebreaks: {
      Buch: '0.5',
      Berg: '0.5',
      Vin: '2',
    },
  },
  {
    place: 3,
    name: 'Odin Åskväder',
    score: 1,
    tiebreaks: {
      Buch: '2.0',
      Berg: '1.0',
      Vin: '1',
    },
  },
  {
    place: 4,
    name: 'Loki Läufeyson',
    score: 1,
    tiebreaks: {
      Buch: '1.5',
      Berg: '0.5',
      Vin: '1',
    },
  },
  {
    place: 5,
    name: 'Björn Järnsida',
    score: 1,
    tiebreaks: {
      Buch: '1.0',
      Berg: '0.0',
      Vin: '1',
    },
  },
  {
    place: 6,
    name: 'Freja Stjärnljus',
    score: 0.5,
    tiebreaks: {
      Buch: '2.5',
      Berg: '0.25',
      Vin: '0',
    },
  },
  {
    place: 7,
    name: 'Sigrid Nattskärm',
    score: 0.5,
    tiebreaks: {
      Buch: '1.5',
      Berg: '0.25',
      Vin: '0',
    },
  },
  {
    place: 8,
    name: 'Tyr Svärdhand',
    score: 0,
    tiebreaks: {
      Buch: '3.0',
      Berg: '0.0',
      Vin: '0',
    },
  },
]

export const CANCELLED_RESULT = {
  standingsR1: [
    {
      place: 1,
      name: 'Odin Åskväder',
      score: 1,
      tiebreaks: {
        Buch: '0.0',
      },
    },
    {
      place: 1,
      name: 'Frej Stormöga',
      score: 1,
      tiebreaks: {
        Buch: '0.0',
      },
    },
    {
      place: 3,
      name: 'Freja Stjärnljus',
      score: 0.5,
      tiebreaks: {
        Buch: '0.5',
      },
    },
    {
      place: 3,
      name: 'Sigrid Nattskärm',
      score: 0.5,
      tiebreaks: {
        Buch: '0.5',
      },
    },
    {
      place: 5,
      name: 'Björn Järnsida',
      score: 0,
      tiebreaks: {
        Buch: '1.0',
      },
    },
    {
      place: 5,
      name: 'Tyr Svärdhand',
      score: 0,
      tiebreaks: {
        Buch: '1.0',
      },
    },
    {
      place: 7,
      name: 'Thor Ödinson',
      score: 0,
      tiebreaks: {
        Buch: '0.0',
      },
    },
    {
      place: 7,
      name: 'Loki Läufeyson',
      score: 0,
      tiebreaks: {
        Buch: '0.0',
      },
    },
  ],
  standingsR2: [
    {
      place: 1,
      name: 'Odin Åskväder',
      score: 2,
      tiebreaks: {
        Buch: '2.0',
      },
    },
    {
      place: 2,
      name: 'Björn Järnsida',
      score: 1,
      tiebreaks: {
        Buch: '2.0',
      },
    },
    {
      place: 2,
      name: 'Frej Stormöga',
      score: 1,
      tiebreaks: {
        Buch: '2.0',
      },
    },
    {
      place: 4,
      name: 'Thor Ödinson',
      score: 1,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 4,
      name: 'Loki Läufeyson',
      score: 1,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 6,
      name: 'Freja Stjärnljus',
      score: 0.5,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 6,
      name: 'Sigrid Nattskärm',
      score: 0.5,
      tiebreaks: {
        Buch: '1.5',
      },
    },
    {
      place: 8,
      name: 'Tyr Svärdhand',
      score: 0,
      tiebreaks: {
        Buch: '2.0',
      },
    },
  ],
}

export const MID_TOURNAMENT_TIEBREAK = {
  standingsBefore: [
    {
      place: 1,
      name: 'Thor Ödinson',
      score: 3,
      tiebreaks: {
        Buch: '5.0',
      },
    },
    {
      place: 2,
      name: 'Frej Stormöga',
      score: 2,
      tiebreaks: {
        Buch: '6.0',
      },
    },
    {
      place: 3,
      name: 'Loki Läufeyson',
      score: 2,
      tiebreaks: {
        Buch: '5.0',
      },
    },
    {
      place: 4,
      name: 'Tyr Svärdhand',
      score: 2,
      tiebreaks: {
        Buch: '3.0',
      },
    },
    {
      place: 5,
      name: 'Björn Järnsida',
      score: 1,
      tiebreaks: {
        Buch: '6.0',
      },
    },
    {
      place: 6,
      name: 'Freja Stjärnljus',
      score: 1,
      tiebreaks: {
        Buch: '4.0',
      },
    },
    {
      place: 7,
      name: 'Odin Åskväder',
      score: 1,
      tiebreaks: {
        Buch: '3.0',
      },
    },
    {
      place: 8,
      name: 'Sigrid Nattskärm',
      score: 0,
      tiebreaks: {
        Buch: '4.0',
      },
    },
  ],
  standingsAfter: [
    {
      place: 1,
      name: 'Thor Ödinson',
      score: 3,
      tiebreaks: {
        Buch: '5.0',
        Berg: '5.0',
        Vin: '3',
      },
    },
    {
      place: 2,
      name: 'Frej Stormöga',
      score: 2,
      tiebreaks: {
        Buch: '6.0',
        Berg: '3.0',
        Vin: '2',
      },
    },
    {
      place: 3,
      name: 'Loki Läufeyson',
      score: 2,
      tiebreaks: {
        Buch: '5.0',
        Berg: '2.0',
        Vin: '2',
      },
    },
    {
      place: 4,
      name: 'Tyr Svärdhand',
      score: 2,
      tiebreaks: {
        Buch: '3.0',
        Berg: '1.0',
        Vin: '2',
      },
    },
    {
      place: 5,
      name: 'Björn Järnsida',
      score: 1,
      tiebreaks: {
        Buch: '6.0',
        Berg: '1.0',
        Vin: '1',
      },
    },
    {
      place: 6,
      name: 'Freja Stjärnljus',
      score: 1,
      tiebreaks: {
        Buch: '4.0',
        Berg: '0.0',
        Vin: '1',
      },
    },
    {
      place: 7,
      name: 'Odin Åskväder',
      score: 1,
      tiebreaks: {
        Buch: '3.0',
        Berg: '0.0',
        Vin: '1',
      },
    },
    {
      place: 8,
      name: 'Sigrid Nattskärm',
      score: 0,
      tiebreaks: {
        Buch: '4.0',
        Berg: '0.0',
        Vin: '0',
      },
    },
  ],
}

export const UNPAIR_REPAIR_CYCLE = {
  pairingsBefore: [
    {
      boardNr: 1,
      white: 'Frej Stormöga',
      black: 'Thor Ödinson',
    },
    {
      boardNr: 2,
      white: 'Björn Järnsida',
      black: 'Loki Läufeyson',
    },
    {
      boardNr: 3,
      white: 'Freja Stjärnljus',
      black: 'Tyr Svärdhand',
    },
    {
      boardNr: 4,
      white: 'Sigrid Nattskärm',
      black: 'Odin Åskväder',
    },
  ],
  pairingsAfter: [
    {
      boardNr: 1,
      white: 'Frej Stormöga',
      black: 'Thor Ödinson',
    },
    {
      boardNr: 2,
      white: 'Björn Järnsida',
      black: 'Loki Läufeyson',
    },
    {
      boardNr: 3,
      white: 'Freja Stjärnljus',
      black: 'Tyr Svärdhand',
    },
    {
      boardNr: 4,
      white: 'Sigrid Nattskärm',
      black: 'Odin Åskväder',
    },
  ],
}

export const DOUBLE_WO_SCORING: any[] = [
  {
    place: 1,
    name: 'Odin Åskväder',
    score: 2,
    tiebreaks: {
      Buch: '2.0',
      Berg: '2.0',
      Vin: '2',
    },
  },
  {
    place: 2,
    name: 'Björn Järnsida',
    score: 1,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '1',
    },
  },
  {
    place: 2,
    name: 'Frej Stormöga',
    score: 1,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '1',
    },
  },
  {
    place: 4,
    name: 'Thor Ödinson',
    score: 1,
    tiebreaks: {
      Buch: '1.5',
      Berg: '0.5',
      Vin: '1',
    },
  },
  {
    place: 4,
    name: 'Loki Läufeyson',
    score: 1,
    tiebreaks: {
      Buch: '1.5',
      Berg: '0.5',
      Vin: '1',
    },
  },
  {
    place: 6,
    name: 'Freja Stjärnljus',
    score: 0.5,
    tiebreaks: {
      Buch: '1.5',
      Berg: '0.25',
      Vin: '0',
    },
  },
  {
    place: 6,
    name: 'Sigrid Nattskärm',
    score: 0.5,
    tiebreaks: {
      Buch: '1.5',
      Berg: '0.25',
      Vin: '0',
    },
  },
  {
    place: 8,
    name: 'Tyr Svärdhand',
    score: 0,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '0',
    },
  },
]

export const ADD_PLAYER_MID_TOURNAMENT = {
  r2Pairings: [
    { boardNr: 1, white: 'Björn Järnsida', black: 'Thor Ödinson' },
    { boardNr: 2, white: 'Odin Åskväder', black: 'Loki Läufeyson' },
    { boardNr: 3, white: 'Frej Stormöga', black: '(bye)' },
  ],
  standingsR2: [
    { place: 1, name: 'Thor Ödinson', score: 2, tiebreaks: {} },
    { place: 2, name: 'Loki Läufeyson', score: 1, tiebreaks: {} },
    { place: 2, name: 'Björn Järnsida', score: 1, tiebreaks: {} },
    { place: 2, name: 'Frej Stormöga', score: 1, tiebreaks: {} },
    { place: 5, name: 'Odin Åskväder', score: 0, tiebreaks: {} },
  ],
}

export const POSTPONED_ONLY_ROUND = {
  standingsR1: [
    { place: 1, name: 'Thor Ödinson', score: 0, tiebreaks: { Buch: '0.0' } },
    { place: 1, name: 'Loki Läufeyson', score: 0, tiebreaks: { Buch: '0.0' } },
    { place: 1, name: 'Björn Järnsida', score: 0, tiebreaks: { Buch: '0.0' } },
    { place: 1, name: 'Odin Åskväder', score: 0, tiebreaks: { Buch: '0.0' } },
    { place: 1, name: 'Frej Stormöga', score: 0, tiebreaks: { Buch: '0.0' } },
    { place: 1, name: 'Tyr Svärdhand', score: 0, tiebreaks: { Buch: '0.0' } },
    { place: 1, name: 'Freja Stjärnljus', score: 0, tiebreaks: { Buch: '0.0' } },
    { place: 1, name: 'Sigrid Nattskärm', score: 0, tiebreaks: { Buch: '0.0' } },
  ],
  r2Pairings: [
    { boardNr: 1, white: 'Björn Järnsida', black: 'Thor Ödinson' },
    { boardNr: 2, white: 'Odin Åskväder', black: 'Loki Läufeyson' },
    { boardNr: 3, white: 'Freja Stjärnljus', black: 'Frej Stormöga' },
    { boardNr: 4, white: 'Sigrid Nattskärm', black: 'Tyr Svärdhand' },
  ],
  standingsR2: [
    { place: 1, name: 'Thor Ödinson', score: 1, tiebreaks: { Buch: '1.0' } },
    { place: 1, name: 'Loki Läufeyson', score: 1, tiebreaks: { Buch: '1.0' } },
    { place: 1, name: 'Frej Stormöga', score: 1, tiebreaks: { Buch: '1.0' } },
    { place: 1, name: 'Tyr Svärdhand', score: 1, tiebreaks: { Buch: '1.0' } },
    { place: 5, name: 'Björn Järnsida', score: 0, tiebreaks: { Buch: '1.0' } },
    { place: 5, name: 'Odin Åskväder', score: 0, tiebreaks: { Buch: '1.0' } },
    { place: 5, name: 'Freja Stjärnljus', score: 0, tiebreaks: { Buch: '1.0' } },
    { place: 5, name: 'Sigrid Nattskärm', score: 0, tiebreaks: { Buch: '1.0' } },
  ],
}

export const WITHDRAWN_PLAYER = {
  standings: [
    {
      place: 1,
      name: 'Thor Ödinson',
      score: 4,
      tiebreaks: {
        Buch: '7.0',
      },
    },
    {
      place: 2,
      name: 'Loki Läufeyson',
      score: 3,
      tiebreaks: {
        Buch: '8.0',
      },
    },
    {
      place: 3,
      name: 'Frej Stormöga',
      score: 2,
      tiebreaks: {
        Buch: '10.0',
      },
    },
    {
      place: 4,
      name: 'Björn Järnsida',
      score: 2,
      tiebreaks: {
        Buch: '9.0',
      },
    },
    {
      place: 5,
      name: 'Tyr Svärdhand',
      score: 2,
      tiebreaks: {
        Buch: '5.0',
      },
    },
    {
      place: 6,
      name: 'Freja Stjärnljus',
      score: 2,
      tiebreaks: {
        Buch: '4.0',
      },
    },
    {
      place: 7,
      name: 'Odin Åskväder',
      score: 1,
      tiebreaks: {
        Buch: '9.0',
      },
    },
    {
      place: 8,
      name: 'Sigrid Nattskärm (utgått r3)',
      score: 0,
      tiebreaks: {
        Buch: '3.0',
      },
    },
  ],
}
