/**
 * Golden-master snapshot data — auto-generated by discovery run.
 * DO NOT EDIT BY HAND.
 */

export const FIDE_MISSING_FIELDS = {
  status: 400,
  error: 'Bad Request',
}

export const NO_ROUNDS_STANDINGS = {
  status: 400,
  error: 'Bad Request',
}

export const SCORE_EXCEED_PPG = {
  status: 400,
  error: 'Bad Request',
}

export const INCOMPLETE_RESULTS = {
  status: 409,
  error: 'CONFLICT',
  message: 'Alla matcher i rond 1 m\u00e5ste ha resultat innan n\u00e4sta rond kan lottas!',
}
