/**
 * Reads the discovery output and generates all snapshot files.
 * Run with: npx tsx e2e/generate-snapshots.ts
 */

import { readFileSync, writeFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const output = readFileSync('/tmp/lotta-discover/output.txt', 'utf-8')
const lines = output.split('\n')

const snapshots: Record<string, string> = {}
for (const line of lines) {
  const eqIdx = line.indexOf('=')
  if (eqIdx > 0 && !line.startsWith('===')) {
    const key = line.substring(0, eqIdx)
    const value = line.substring(eqIdx + 1)
    snapshots[key] = value
  }
}

function formatJson(jsonStr: string): string {
  const parsed = JSON.parse(jsonStr)
  return JSON.stringify(parsed, null, 2)
}

function writeSnapshot(filename: string, exports: Record<string, { key: string; type: string }>) {
  let content =
    '/**\n * Golden-master snapshot data — auto-generated by discovery run.\n * DO NOT EDIT BY HAND.\n */\n\n'
  for (const [exportName, { key, type }] of Object.entries(exports)) {
    const raw = snapshots[key]
    if (!raw) {
      console.error(`Missing key: ${key}`)
      continue
    }
    if (type === 'string') {
      content += `export const ${exportName}: string = ${raw}\n\n`
    } else {
      content += `export const ${exportName}: ${type} = ${formatJson(raw)}\n\n`
    }
  }
  const filepath = path.join(__dirname, filename)
  writeFileSync(filepath, content, 'utf-8')
  console.log(`Wrote ${filepath}`)
}

writeSnapshot('results-snapshots.ts', {
  RESULTS_ROUND2_GAMES: { key: 'RESULTS_ROUND2_GAMES', type: 'any[]' },
  RESULTS_STANDINGS_AFTER_R2: { key: 'RESULTS_STANDINGS_AFTER_R2', type: 'any[]' },
  RESULTS_STANDINGS_AFTER_R3: { key: 'RESULTS_STANDINGS_AFTER_R3', type: 'any[]' },
})

writeSnapshot('standings-snapshots.ts', {
  STANDINGS_8TB_BY_ROUND: { key: 'STANDINGS_8TB_BY_ROUND', type: 'any[][]' },
  STANDINGS_INBORDES: { key: 'STANDINGS_INBORDES', type: 'any[]' },
  STANDINGS_MANUELL: { key: 'STANDINGS_MANUELL', type: 'any[]' },
})

writeSnapshot('club-standings-snapshots.ts', {
  CLUB_STANDINGS_BY_ROUND: { key: 'CLUB_STANDINGS_BY_ROUND', type: 'any[][]' },
  CLUB_STANDINGS_ALL_DRAWS: { key: 'CLUB_STANDINGS_ALL_DRAWS', type: 'any[]' },
})

writeSnapshot('settings-snapshots.ts', {
  SETTINGS_FIRST_LAST_STANDINGS: { key: 'SETTINGS_FIRST_LAST_STANDINGS', type: 'any[]' },
  SETTINGS_LAST_FIRST_STANDINGS: { key: 'SETTINGS_LAST_FIRST_STANDINGS', type: 'any[]' },
  SETTINGS_QUICK_RATING: { key: 'SETTINGS_QUICK_RATING', type: 'any[]' },
  SETTINGS_QUICK_THEN_ELO_FALLBACK: { key: 'SETTINGS_QUICK_THEN_ELO_FALLBACK', type: 'any[]' },
  SETTINGS_POINTS_PER_GAME_2: { key: 'SETTINGS_POINTS_PER_GAME_2', type: 'any[]' },
})

writeSnapshot('chess4-snapshots.ts', {
  CHESS4_GAME_SCORING: { key: 'CHESS4_GAME_SCORING', type: 'any[]' },
  CHESS4_STANDINGS_FINAL: { key: 'CHESS4_STANDINGS_FINAL', type: 'any[]' },
  CHESS4_STANDINGS_BY_ROUND: { key: 'CHESS4_STANDINGS_BY_ROUND', type: 'any[][]' },
  CHESS4_PUBLISH_HTML: { key: 'CHESS4_PUBLISH_HTML', type: 'string' },
})

writeSnapshot('exports-snapshots.ts', {
  EXPORT_PLAYERS_TSV: { key: 'EXPORT_PLAYERS_TSV', type: 'string' },
  EXPORT_FIDE_REPORT: { key: 'EXPORT_FIDE_REPORT', type: 'string' },
  EXPORT_LIVECHESS_UNFINISHED: { key: 'EXPORT_LIVECHESS_UNFINISHED', type: 'string' },
  EXPORT_LIVECHESS_FINISHED: { key: 'EXPORT_LIVECHESS_FINISHED', type: 'string' },
  PUBLISH_PAIRINGS_HTML: { key: 'PUBLISH_PAIRINGS_HTML', type: 'string' },
  PUBLISH_STANDINGS_HTML: { key: 'PUBLISH_STANDINGS_HTML', type: 'string' },
  PUBLISH_PLAYERS_HTML: { key: 'PUBLISH_PLAYERS_HTML', type: 'string' },
  PUBLISH_CLUB_STANDINGS_HTML: { key: 'PUBLISH_CLUB_STANDINGS_HTML', type: 'string' },
  PUBLISH_ALPHABETICAL_HTML: { key: 'PUBLISH_ALPHABETICAL_HTML', type: 'string' },
  PUBLISH_CROSS_TABLE_HTML: { key: 'PUBLISH_CROSS_TABLE_HTML', type: 'string' },
})

console.log('All snapshot files generated!')
