/**
 * Golden-master snapshot data — auto-generated by discovery run.
 * DO NOT EDIT BY HAND.
 */

export const BYE_ROTATION: any[] = [
  {
    roundNr: 1,
    pairings: [
      { boardNr: 1, white: 'B Beta', black: 'A Alfa' },
      { boardNr: 2, white: 'D Delta', black: 'C Gamma' },
      { boardNr: 3, white: 'E Epsilon', black: '(bye)' },
    ],
    byeRecipient: 'E Epsilon',
  },
  {
    roundNr: 2,
    pairings: [
      { boardNr: 1, white: 'A Alfa', black: 'E Epsilon' },
      { boardNr: 2, white: 'C Gamma', black: 'B Beta' },
      { boardNr: 3, white: 'D Delta', black: '(bye)' },
    ],
    byeRecipient: 'D Delta',
  },
  {
    roundNr: 3,
    pairings: [
      { boardNr: 1, white: 'A Alfa', black: 'D Delta' },
      { boardNr: 2, white: 'E Epsilon', black: 'B Beta' },
      { boardNr: 3, white: 'C Gamma', black: '(bye)' },
    ],
    byeRecipient: 'C Gamma',
  },
  {
    roundNr: 4,
    pairings: [
      { boardNr: 1, white: 'C Gamma', black: 'A Alfa' },
      { boardNr: 2, white: 'E Epsilon', black: 'D Delta' },
      { boardNr: 3, white: 'B Beta', black: '(bye)' },
    ],
    byeRecipient: 'B Beta',
  },
  {
    roundNr: 5,
    pairings: [
      { boardNr: 1, white: 'D Delta', black: 'B Beta' },
      { boardNr: 2, white: 'E Epsilon', black: 'C Gamma' },
      { boardNr: 3, white: 'A Alfa', black: '(bye)' },
    ],
    byeRecipient: 'A Alfa',
  },
]

export const BERGER_3P: any[] = [
  {
    roundNr: 1,
    pairings: [
      { boardNr: 1, white: 'A Alfa', black: '(bye)' },
      { boardNr: 2, white: 'B Beta', black: 'C Gamma' },
    ],
    byeRecipient: 'A Alfa',
  },
  {
    roundNr: 2,
    pairings: [
      { boardNr: 1, white: '(bye)', black: 'C Gamma' },
      { boardNr: 2, white: 'A Alfa', black: 'B Beta' },
    ],
    byeRecipient: 'C Gamma',
  },
  {
    roundNr: 3,
    pairings: [
      { boardNr: 1, white: 'B Beta', black: '(bye)' },
      { boardNr: 2, white: 'C Gamma', black: 'A Alfa' },
    ],
    byeRecipient: 'B Beta',
  },
]

export const BERGER_5P: any[] = [
  {
    roundNr: 1,
    pairings: [
      { boardNr: 1, white: 'A Alfa', black: '(bye)' },
      { boardNr: 2, white: 'C Gamma', black: 'D Delta' },
      { boardNr: 3, white: 'B Beta', black: 'E Epsilon' },
    ],
    byeRecipient: 'A Alfa',
  },
  {
    roundNr: 2,
    pairings: [
      { boardNr: 1, white: '(bye)', black: 'D Delta' },
      { boardNr: 2, white: 'A Alfa', black: 'B Beta' },
      { boardNr: 3, white: 'E Epsilon', black: 'C Gamma' },
    ],
    byeRecipient: 'D Delta',
  },
  {
    roundNr: 3,
    pairings: [
      { boardNr: 1, white: 'B Beta', black: '(bye)' },
      { boardNr: 2, white: 'D Delta', black: 'E Epsilon' },
      { boardNr: 3, white: 'C Gamma', black: 'A Alfa' },
    ],
    byeRecipient: 'B Beta',
  },
  {
    roundNr: 4,
    pairings: [
      { boardNr: 1, white: '(bye)', black: 'E Epsilon' },
      { boardNr: 2, white: 'B Beta', black: 'C Gamma' },
      { boardNr: 3, white: 'A Alfa', black: 'D Delta' },
    ],
    byeRecipient: 'E Epsilon',
  },
  {
    roundNr: 5,
    pairings: [
      { boardNr: 1, white: 'C Gamma', black: '(bye)' },
      { boardNr: 2, white: 'E Epsilon', black: 'A Alfa' },
      { boardNr: 3, white: 'D Delta', black: 'B Beta' },
    ],
    byeRecipient: 'C Gamma',
  },
]

export const MONRAD_COLOR: any[] = [
  { name: 'A Alfa', whites: 4, blacks: 3 },
  { name: 'B Beta', whites: 3, blacks: 4 },
  { name: 'C Gamma', whites: 3, blacks: 4 },
  { name: 'D Delta', whites: 3, blacks: 4 },
  { name: 'E Epsilon', whites: 3, blacks: 4 },
  { name: 'F Zeta', whites: 4, blacks: 3 },
  { name: 'G Eta', whites: 4, blacks: 3 },
  { name: 'H Theta', whites: 4, blacks: 3 },
]

export const NS_COLOR: any[] = [
  { name: 'A Alfa', whites: 4, blacks: 3 },
  { name: 'B Beta', whites: 3, blacks: 4 },
  { name: 'C Gamma', whites: 4, blacks: 3 },
  { name: 'D Delta', whites: 4, blacks: 3 },
  { name: 'E Epsilon', whites: 3, blacks: 4 },
  { name: 'F Zeta', whites: 4, blacks: 3 },
  { name: 'G Eta', whites: 3, blacks: 4 },
  { name: 'H Theta', whites: 3, blacks: 4 },
]

export const IDENTICAL_RATINGS: any[] = [
  { boardNr: 1, white: 'B Beta', black: 'A Alfa' },
  { boardNr: 2, white: 'D Delta', black: 'C Gamma' },
]
