/**
 * Golden-master snapshot data — auto-generated by discovery run.
 * DO NOT EDIT BY HAND.
 */

export const SETTINGS_FIRST_LAST_STANDINGS: any[] = [
  {
    place: 1,
    name: 'Thor Ödinson',
    rating: 2100,
    score: 1,
  },
  {
    place: 1,
    name: 'Björn Järnsida',
    rating: 1800,
    score: 1,
  },
  {
    place: 3,
    name: 'Loki Läufeyson',
    rating: 1950,
    score: 0,
  },
  {
    place: 3,
    name: 'Odin Åskväder',
    rating: 1750,
    score: 0,
  },
]

export const SETTINGS_LAST_FIRST_STANDINGS: any[] = [
  {
    place: 1,
    name: 'Ödinson Thor',
    rating: 2100,
    score: 1,
  },
  {
    place: 1,
    name: 'Järnsida Björn',
    rating: 1800,
    score: 1,
  },
  {
    place: 3,
    name: 'Läufeyson Loki',
    rating: 1950,
    score: 0,
  },
  {
    place: 3,
    name: 'Åskväder Odin',
    rating: 1750,
    score: 0,
  },
]

export const SETTINGS_QUICK_RATING: any[] = [
  {
    place: 1,
    name: 'Thor Ödinson',
    rating: 1500,
    score: 1,
  },
  {
    place: 1,
    name: 'Björn Järnsida',
    rating: 1500,
    score: 1,
  },
  {
    place: 3,
    name: 'Loki Läufeyson',
    rating: 1500,
    score: 0,
  },
  {
    place: 3,
    name: 'Odin Åskväder',
    rating: 1500,
    score: 0,
  },
]

export const SETTINGS_QUICK_THEN_ELO_FALLBACK: any[] = [
  {
    place: 1,
    name: 'Loki Läufeyson',
    rating: 1950,
    score: 1,
  },
  {
    place: 1,
    name: 'Odin Åskväder',
    rating: 1750,
    score: 1,
  },
  {
    place: 3,
    name: 'Thor Ödinson',
    rating: 1800,
    score: 0,
  },
  {
    place: 3,
    name: 'Björn Järnsida',
    rating: 1600,
    score: 0,
  },
]

export const SETTINGS_POINTS_PER_GAME_2: any[] = [
  {
    place: 1,
    name: 'Thor Ödinson',
    rating: 2100,
    score: 6,
  },
  {
    place: 2,
    name: 'Loki Läufeyson',
    rating: 1950,
    score: 4,
  },
  {
    place: 3,
    name: 'Björn Järnsida',
    rating: 1800,
    score: 2,
  },
  {
    place: 4,
    name: 'Odin Åskväder',
    rating: 1750,
    score: 0,
  },
]
