/**
 * Golden-master snapshot data — auto-generated by discovery run.
 * DO NOT EDIT BY HAND.
 */

export const QUICK_THEN_ELO: any[] = [
  {
    place: 1,
    name: 'Thor Ödinson',
    score: 2,
    tiebreaks: {
      Buch: '2.0',
      Berg: '2.0',
      Vin: '2',
    },
  },
  {
    place: 1,
    name: 'Frej Stormöga',
    score: 2,
    tiebreaks: {
      Buch: '2.0',
      Berg: '2.0',
      Vin: '2',
    },
  },
  {
    place: 3,
    name: 'Loki Läufeyson',
    score: 1,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '1',
    },
  },
  {
    place: 3,
    name: 'Björn Järnsida',
    score: 1,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '1',
    },
  },
  {
    place: 3,
    name: 'Tyr Svärdhand',
    score: 1,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '1',
    },
  },
  {
    place: 3,
    name: 'Freja Stjärnljus',
    score: 1,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '1',
    },
  },
  {
    place: 7,
    name: 'Odin Åskväder',
    score: 0,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '0',
    },
  },
  {
    place: 7,
    name: 'Sigrid Nattskärm',
    score: 0,
    tiebreaks: {
      Buch: '2.0',
      Berg: '0.0',
      Vin: '0',
    },
  },
]

export const MEDIAN_BUCHHOLZ_2R: any[] = [
  { place: 1, name: 'Loki Läufeyson', score: 2, tiebreaks: { Buch: '1.5', 'M.Buch': '1.5' } },
  { place: 2, name: 'Frej Stormöga', score: 1.5, tiebreaks: { Buch: '2.0', 'M.Buch': '2.0' } },
  { place: 3, name: 'Björn Järnsida', score: 1, tiebreaks: { Buch: '3.0', 'M.Buch': '3.0' } },
  { place: 4, name: 'Tyr Svärdhand', score: 1, tiebreaks: { Buch: '2.0', 'M.Buch': '2.0' } },
  { place: 5, name: 'Sigrid Nattskärm', score: 1, tiebreaks: { Buch: '1.5', 'M.Buch': '1.5' } },
  { place: 6, name: 'Odin Åskväder', score: 1, tiebreaks: { Buch: '1.0', 'M.Buch': '1.0' } },
  { place: 7, name: 'Thor Ödinson', score: 0.5, tiebreaks: { Buch: '3.0', 'M.Buch': '3.0' } },
  { place: 8, name: 'Freja Stjärnljus', score: 0, tiebreaks: { Buch: '2.0', 'M.Buch': '2.0' } },
]

export const SSF_BUCHHOLZ_BYES: any[] = [
  { place: 1, name: 'Thor Ödinson', score: 3, tiebreaks: { Buch: '4.0', SSFBuch: '4.0' } },
  { place: 2, name: 'Björn Järnsida', score: 2, tiebreaks: { Buch: '5.0', SSFBuch: '5.0' } },
  { place: 3, name: 'Loki Läufeyson', score: 2, tiebreaks: { Buch: '3.0', SSFBuch: '4.0' } },
  { place: 4, name: 'Frej Stormöga', score: 2, tiebreaks: { Buch: '2.0', SSFBuch: '3.0' } },
  { place: 5, name: 'Freja Stjärnljus', score: 1, tiebreaks: { Buch: '5.0', SSFBuch: '5.0' } },
  { place: 6, name: 'Odin Åskväder', score: 1, tiebreaks: { Buch: '4.0', SSFBuch: '4.0' } },
  { place: 6, name: 'Tyr Svärdhand', score: 1, tiebreaks: { Buch: '4.0', SSFBuch: '4.0' } },
]

export const INBORDES_MOTE: any[] = [
  { place: 1, name: 'Björn Järnsida', score: 3.5, tiebreaks: { Buch: '8.0', Inb: '0.0' } },
  { place: 2, name: 'Odin Åskväder', score: 2.5, tiebreaks: { Buch: '7.5', Inb: '0.0' } },
  { place: 3, name: 'Loki Läufeyson', score: 2, tiebreaks: { Buch: '8.5', Inb: '0.0' } },
  { place: 4, name: 'Tyr Svärdhand', score: 2, tiebreaks: { Buch: '7.5', Inb: '0.0' } },
  { place: 5, name: 'Frej Stormöga', score: 1.5, tiebreaks: { Buch: '8.5', Inb: '0.0' } },
  { place: 6, name: 'Thor Ödinson', score: 0.5, tiebreaks: { Buch: '8.0', Inb: '0.0' } },
]

export const PROGRESSIVE_TIEBREAK: any[] = [
  { place: 1, name: 'Freja Stjärnljus', score: 3, tiebreaks: { Buch: '5.0', Prog: '6.0' } },
  { place: 2, name: 'Loki Läufeyson', score: 2, tiebreaks: { Buch: '6.0', Prog: '5.0' } },
  { place: 3, name: 'Tyr Svärdhand', score: 1.5, tiebreaks: { Buch: '5.0', Prog: '3.5' } },
  { place: 4, name: 'Björn Järnsida', score: 1.5, tiebreaks: { Buch: '4.0', Prog: '3.5' } },
  { place: 5, name: 'Sigrid Nattskärm', score: 1.5, tiebreaks: { Buch: '4.0', Prog: '2.0' } },
  { place: 6, name: 'Thor Ödinson', score: 1.5, tiebreaks: { Buch: '3.0', Prog: '2.0' } },
  { place: 7, name: 'Odin Åskväder', score: 0.5, tiebreaks: { Buch: '4.5', Prog: '1.0' } },
  { place: 7, name: 'Frej Stormöga', score: 0.5, tiebreaks: { Buch: '4.5', Prog: '1.0' } },
]

export const SVARTA_PARTIER: any[] = [
  { place: 1, name: 'Thor Ödinson', score: 4, tiebreaks: { Buch: '9.0', Svart: '3' } },
  { place: 2, name: 'Loki Läufeyson', score: 3, tiebreaks: { Buch: '10.0', Svart: '3' } },
  { place: 3, name: 'Frej Stormöga', score: 2, tiebreaks: { Buch: '10.0', Svart: '2' } },
  { place: 4, name: 'Björn Järnsida', score: 2, tiebreaks: { Buch: '9.0', Svart: '1' } },
  { place: 5, name: 'Tyr Svärdhand', score: 2, tiebreaks: { Buch: '7.0', Svart: '3' } },
  { place: 6, name: 'Odin Åskväder', score: 2, tiebreaks: { Buch: '6.0', Svart: '2' } },
  { place: 7, name: 'Freja Stjärnljus', score: 1, tiebreaks: { Buch: '6.0', Svart: '1' } },
  { place: 8, name: 'Sigrid Nattskärm', score: 0, tiebreaks: { Buch: '7.0', Svart: '1' } },
]

export const VINSTER_WO: any[] = [
  { place: 1, name: 'Tyr Svärdhand', score: 2, tiebreaks: { Buch: '2.0', Vin: '2' } },
  { place: 2, name: 'Loki Läufeyson', score: 2, tiebreaks: { Buch: '1.0', Vin: '2' } },
  { place: 3, name: 'Frej Stormöga', score: 1, tiebreaks: { Buch: '2.0', Vin: '1' } },
  { place: 3, name: 'Freja Stjärnljus', score: 1, tiebreaks: { Buch: '2.0', Vin: '1' } },
  { place: 5, name: 'Thor Ödinson', score: 1, tiebreaks: { Buch: '1.0', Vin: '1' } },
  { place: 5, name: 'Björn Järnsida', score: 1, tiebreaks: { Buch: '1.0', Vin: '1' } },
  { place: 7, name: 'Sigrid Nattskärm', score: 0, tiebreaks: { Buch: '2.0', Vin: '0' } },
  { place: 8, name: 'Odin Åskväder', score: 0, tiebreaks: { Buch: '1.0', Vin: '0' } },
]

export const PRESTATIONSRATING_LASK: any[] = [
  { place: 1, name: 'Freja Stjärnljus', score: 3, tiebreaks: { Pres: '2300' } },
  { place: 2, name: 'Björn Järnsida', score: 2, tiebreaks: { Pres: '1625' } },
  { place: 2, name: 'Tyr Svärdhand', score: 2, tiebreaks: { Pres: '1625' } },
  { place: 4, name: 'Loki Läufeyson', score: 1.5, tiebreaks: { Pres: '1500' } },
  { place: 4, name: 'Odin Åskväder', score: 1.5, tiebreaks: { Pres: '1500' } },
  { place: 6, name: 'Thor Ödinson', score: 1, tiebreaks: { Pres: '1375' } },
  { place: 7, name: 'Frej Stormöga', score: 0.5, tiebreaks: { Pres: '1216' } },
  { place: 7, name: 'Sigrid Nattskärm', score: 0.5, tiebreaks: { Pres: '1216' } },
]

export const CHESS4_CLUB_SCALING: any[] = [
  { place: 1, club: 'SK Tiny', playerCount: 2, chess4Members: 5, score: 88 },
  { place: 2, club: 'SK Small', playerCount: 2, chess4Members: 10, score: 64 },
  { place: 3, club: 'SK Medium', playerCount: 2, chess4Members: 15, score: 43 },
  { place: 4, club: 'SK Large', playerCount: 2, chess4Members: 20, score: 20 },
]

export const TIEBREAK_BYES_WO: any[] = [
  {
    place: 1,
    name: 'Thor Ödinson',
    score: 3.5,
    tiebreaks: {
      Buch: '5.5',
      SSFBuch: '6.5',
      'M.Buch': '5.5',
      Berg: '5.75',
      Vin: '3',
    },
  },
  {
    place: 2,
    name: 'Loki Läufeyson',
    score: 3,
    tiebreaks: {
      Buch: '6.0',
      SSFBuch: '7.5',
      'M.Buch': '6.0',
      Berg: '5.5',
      Vin: '3',
    },
  },
  {
    place: 3,
    name: 'Frej Stormöga',
    score: 3,
    tiebreaks: {
      Buch: '3.0',
      SSFBuch: '5.0',
      'M.Buch': '3.0',
      Berg: '3.0',
      Vin: '2',
    },
  },
  {
    place: 4,
    name: 'Björn Järnsida',
    score: 2,
    tiebreaks: {
      Buch: '8.0',
      SSFBuch: '9.5',
      'M.Buch': '8.0',
      Berg: '4.5',
      Vin: '2',
    },
  },
  {
    place: 5,
    name: 'Tyr Svärdhand',
    score: 2,
    tiebreaks: {
      Buch: '5.0',
      SSFBuch: '7.0',
      'M.Buch': '5.0',
      Berg: '1.0',
      Vin: '1',
    },
  },
  {
    place: 6,
    name: 'Odin Åskväder',
    score: 1.5,
    tiebreaks: {
      Buch: '7.5',
      SSFBuch: '8.5',
      'M.Buch': '7.5',
      Berg: '1.75',
      Vin: '0',
    },
  },
  {
    place: 7,
    name: 'Freja Stjärnljus',
    score: 1,
    tiebreaks: {
      Buch: '5.5',
      SSFBuch: '8.5',
      'M.Buch': '5.5',
      Berg: '0.0',
      Vin: '0',
    },
  },
]
